server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  jwt:
    secret: ${JWT_SECRET}
    expire-seconds: ${JWT_EXPIRE_SECONDS:7200}
    issuer: ${JWT_ISSUER:resident-management}
